# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2014
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2014&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def search(limit):
    entry = [1]
    cnt = 0
    for p in primes:
        new = []
        for e in entry:
            v = e
            while v * p <= limit and cnt <= k:
                v *= p
                new.append(v)
                cnt += 1
            if cnt > k:
                return k + 1
        entry += new
    return cnt


n, k = map(int, input().split())
primes = list(map(int, input().split()))
left = 1
right = 2 ** 31 - 1
ans = 2 ** 31 - 1
while left <= right:
    mid = (left + right) // 2
    v = search(mid)
    if v > k:
        right = mid - 1
    elif v < k:
        left = mid + 1
    else:
        if mid < ans:
            ans = mid
        right = mid - 1
print(ans)
