# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1806
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1806&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m = map(int, input().split())
arr = list(map(int, input().split()))
ans = 0
l = r = 0
v = arr[0]
while l <= r < n:
    if v >= m:
        length = r - l + 1
        if ans == 0 or length < ans:
            ans = length
        v -= arr[l]
        l += 1
    else:
        r += 1
        if r < n:
            v += arr[r]
print(ans)
