# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1033
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1033&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from math import gcd, lcm

n = int(input())
graph = [[] for _ in range(n)]
for _ in range(n - 1):
    x, y, p, q = map(int, input().split())
    g = gcd(p, q)
    p //= g
    q //= g
    graph[x].append((y, p, q))
    graph[y].append((x, q, p))
v = [0] * n
v[0] = 1
que = [0]
for idx in que:
    for adj, p, q in graph[idx]:
        if v[adj] == 0:
            new = lcm(v[idx], p, q)
            ratio = new // v[idx]
            for i in range(n):
                if v[i] != 0:
                    v[i] *= ratio
            v[adj] = new // p * q
            que.append(adj)
g = gcd(*v)
print(*(v_i // g for v_i in v))
