# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16987
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16987&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def take(idx):
    global max_broken

    if idx == n:
        max_broken = max(max_broken, sum(strength[i] <= 0 for i in range(n)))
        return
    if strength[idx] <= 0:
        take(idx + 1)
        return
    flag = True
    for i in range(n):
        if i == idx or strength[i] <= 0:
            continue
        flag = False
        strength[idx] -= weight[i]
        strength[i] -= weight[idx]
        take(idx + 1)
        strength[idx] += weight[i]
        strength[i] += weight[idx]
    if flag:
        max_broken = max(max_broken, n - 1)


n = int(input())
strength = [0] * n
weight = [0] * n
for i in range(n):
    x, y = map(int, input().split())
    strength[i] = x
    weight[i] = y
max_broken = 0
take(0)
print(max_broken)
