# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14391
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14391&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def dfs(v, entry):
    x, y = divmod(v, m)
    if x == n - 1 and y == m - 1:
        global ans
        if sum(entry) > ans:
            ans = sum(entry)
        return
    if visited[x][y]:
        dfs(v + 1, entry)
        return
    cands = []
    nx = x
    ny = y
    e = []
    while nx < n:
        if visited[nx][y]:
            break
        e.append((nx, y))
        cands.append(list(e))
        nx += 1
    e = []
    while ny < m:
        if visited[x][ny]:
            break
        e.append((x, ny))
        cands.append(list(e))
        ny += 1
    for cand in cands:
        now = ''
        for x, y in cand:
            visited[x][y] = True
            now += board[x][y]
        dfs(v + 1, entry + [int(now)])
        for x, y in cand:
            visited[x][y] = False

n, m = map(int, input().split())
board = [input() for _ in range(n)]
ans = sum(map(int, board))
visited = [[False] * m for _ in range(n)]
dfs(0, [])
print(ans)
