# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1561
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1561&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from math import lcm

n, m = map(int, input().split())
arr = list(map(int, input().split()))
p = lcm(*arr)
tmp = 0
for c in arr:
    tmp += p // c
n %= tmp
left = 0
right = p - 1
t = -1
while left <= right:
    mid = (left + right) // 2
    tmp = 0
    for c in arr:
        tmp += mid // c + 1
    if tmp >= n:
        t = mid
        right = mid - 1
    else:
        left = mid + 1
e = []
for i, c in enumerate(arr, start=1):
    n -= t // c
    if t % c == 0:
        e.append(i)
    else:
        n -= 1
print(e[n - 1])
