# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/4991
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=4991&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from collections import deque

input = stdin.readline
INF = float('inf')


def main(n, m):
    board = [[-1] * m for _ in range(n)]
    idx = 0
    for i in range(n):
        row = input()
        for j in range(m):
            if row[j] == '*':
                idx += 1
                board[i][j] = idx
            elif row[j] == 'o':
                board[i][j] = 0
            elif row[j] == 'x':
                board[i][j] = -2
    dist = [[-1] * (idx + 1) for _ in range(idx + 1)]
    dx = [0, 0, 1, -1]
    dy = [1, -1, 0, 0]
    for i in range(n):
        for j in range(m):
            if board[i][j] < 0:
                continue
            d_idx = board[i][j]
            dist[d_idx][d_idx] = 0
            q = deque([(i, j, 0)])
            visited = [[False] * m for _ in range(n)]
            visited[i][j] = True
            while q:
                x, y, d = q.popleft()
                for k in range(4):
                    nx = x + dx[k]
                    ny = y + dy[k]
                    if 0 <= nx < n and 0 <= ny < m and not visited[nx][ny] and board[nx][ny] >= -1:
                        visited[nx][ny] = True
                        nd = d + 1
                        if board[nx][ny] >= 0:
                            dist[d_idx][board[nx][ny]] = nd
                        q.append((nx, ny, nd))
    dp = [[INF] * idx for _ in range(1 << idx)]
    for i in range(1, idx + 1):
        if dist[0][i] != -1:
            dp[1 << (i - 1)][i - 1] = dist[0][i]
        else:
            print(-1)
            return
    for s in range(1 << idx):
        for u in range(idx):
            if not (s & (1 << u)):
                continue
            for v in range(idx):
                if s & (1 << v):
                    continue
                if dist[u + 1][v + 1] == -1:
                    continue
                ns = s | (1 << v)
                nd = dp[s][u] + dist[u + 1][v + 1]
                if dp[ns][v] > nd:
                    dp[ns][v] = nd
    print(min(dp[-1]))


if __name__ == "__main__":
    while True:
        n, m = map(int, input().split())
        if n == 0 and m == 0:
            break
        main(m, n)
