# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17835
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17835&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import heappop, heappush

input = stdin.readline
INF = float('inf')


def dijkstra(starts):
    dist = [INF] * (n + 1)
    dist[0] = -1
    for idx in starts:
        dist[idx] = 0
    q = [(0, idx) for idx in starts]
    while q:
        c, idx = heappop(q)
        if dist[idx] < c:
            continue
        for adj, ex in graph[idx]:
            nc = c + ex
            if dist[adj] > nc:
                dist[adj] = nc
                heappush(q, (nc, adj))
    return dist


n, m, k = map(int, input().split())
graph = [[] for _ in range(n + 1)]
for _ in range(m):
    x, y, d = map(int, input().split())
    graph[y].append((x, d))
starts = list(map(int, input().split()))
dist = dijkstra(starts)
mv = max(dist[1:])
print(dist.index(mv))
print(mv)
