# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17616
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17616&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def search(start, graph):
    visited = [False] * (n + 1)
    q = [start]
    visited[start] = True
    cnt = 0
    while q:
        idx = q.pop()
        for adj in graph[idx]:
            if not visited[adj]:
                visited[adj] = True
                q.append(adj)
                cnt += 1
    return cnt


n, m, init = map(int, input().split())
graph = [[] for _ in range(n + 1)]
graph_rev = [[] for _ in range(n + 1)]
for _ in range(m):
    x, y = map(int, input().split())
    graph[x].append(y)
    graph_rev[y].append(x)
left = search(init, graph_rev)
right = search(init, graph)
print(1 + left, n - right)
