# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/21318
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=21318&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
arr = list(map(int, input().split())) + [float('inf')]
qs = [tuple(map(int, input().split())) for _ in range(int(input()))]
prefix = [0] * (n + 1)
for i in range(n):
    prefix[i + 1] = prefix[i] + (arr[i] > arr[i + 1])
for l, r in qs:
    print(prefix[r - 1] - prefix[l - 1])
