# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14427
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14427&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import *

input = stdin.readline

n = int(input())
arr = list(map(int, input().split()))
q = int(input())
queries = [tuple(map(int, input().split())) for _ in range(q)]

h = [(a, i) for i, a in enumerate(arr)]
heapify(h)
for s, *k in queries:
    if s == 1:
        a, b = k
        heappush(h, (b, a - 1))
        arr[a - 1] = b
    else:
        a, i = heappop(h)
        while a != arr[i]:
            a, i = heappop(h)
        print(i + 1)
        heappush(h, (a, i))
