# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1074
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1074&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def s(n,x,y):return x%2*2+y%2+4*s(n-1,x//2,y//2)if n else 0
print(s(*map(int,input().split())))
