# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/31778
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=31778&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, k = map(int, input().split())
is_c = [c == 'C' for c in input()]
cp = 0
pp = n - 1
while cp < pp and k:
    while cp < n and not is_c[cp]:
        cp += 1
    while pp >= 0 and is_c[pp]:
        pp -= 1
    if cp < pp:
        is_c[cp] = False
        is_c[pp] = True
        k -= 1
ans = 0
p_count = 0
for c in is_c:
    if c:
        ans += p_count * (p_count - 1) // 2
    else:
        p_count += 1
print(ans)
