# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2230
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2230&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
arr = [int(input()) for _ in range(n)]
arr.sort()
ans = arr[-1] - arr[0]
left = 0
right = 1
while right < n:
    l, r = arr[left], arr[right]
    if r - l >= m:
        ans = min(ans, r - l)
        left += 1
    else:
        right += 1
    if right == left:
        right += 1
print(ans)
