# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/3078
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=3078&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from collections import deque

input = stdin.readline

n, k = map(int, input().split())
arr = [len(input().rstrip()) for _ in range(n)]
dqs = [deque() for _ in range(21)]
ans = 0
for i, v in enumerate(arr):
    while dqs[v] and dqs[v][0] < i - k:
        dqs[v].popleft()
    ans += len(dqs[v])
    dqs[v].append(i)
print(ans)
