# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2696
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2696&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
import heapq

input = stdin.readline

tcs = []
for _ in range(int(input())):
    n = int(input())
    arr = []
    for _ in range(n // 10 + 1):
        arr += list(map(int, input().split()))
    tcs.append(arr)
for tc in tcs:
    ans = []
    mid = None
    left = []
    right = []
    for i, v in enumerate(tc):
        if mid is None:
            mid = v
        elif v < mid:
            heapq.heappush(left, -v)
        else:
            heapq.heappush(right, v)
        if i % 2 == 0:
            if len(left) > len(right):
                heapq.heappush(right, mid)
                mid = -heapq.heappop(left)
            elif len(left) < len(right):
                heapq.heappush(left, -mid)
                mid = heapq.heappop(right)
            ans.append(mid)
    print(len(ans))
    for i in range(0, len(ans), 10):
        print(*ans[i:i + 10])
