# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1285
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1285&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
board = [[c == 'H' for c in input()] for _ in range(n)]
ans = n * n
for bits in range(1 << (n - 1)):
    tmp = 0
    for i in range(n):
        head = 0
        for j in range(n):
            head += board[i][j] ^ (bits >> j & 1)
        tmp += min(head, n - head)
    if tmp < ans:
        ans = tmp
print(ans)
