# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/19539
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=19539&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
cnt = sum([a % 2 for a in arr])
print("YES" if (s := sum(arr)) % 3 == 0 and cnt <= s // 3 else "NO")
