# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2170
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2170&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
arr = [tuple(map(int, input().split())) for _ in range(n)]
arr.sort()
ans = 0
px, py = arr[0]
for x, y in arr[1:]:
    if x > py:
        ans += py - px
        px, py = x, y 
    else:
        py = max(py, y)
ans += py - px
print(ans)
