# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1477
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1477&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m, l = map(int, input().split())
arr = list(map(int, input().split())) + [0, l]
arr.sort()
left = 1
right = l
ans = 0
while left <= right:
    mid = (left + right) // 2
    tmp = 0
    for i in range(1, n + 2):
        tmp += (arr[i] - arr[i - 1] - 1) // mid
    if tmp > m:
        left = mid + 1
    else:
        right = mid - 1
        ans = mid
print(ans)
