# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2023
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2023&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def check_prime(n):
    if n == 1:
        return False
    if n % 2 == 0:
        return False
    for i in range(3, int(n**0.5) + 2, 2):
        if n % i == 0:
            return False
    return True

n = int(input())
q = [2, 3, 5, 7]
tail = [1, 3, 7, 9]
for _ in range(n - 1):
    nq = []
    for i in q:
        for j in tail:
            t = i * 10 + j
            if check_prime(t):
                nq.append(t)
    q = nq
q.sort()
print(*q, sep='\n')
