# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2661
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2661&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def solve(n: int):
    def _solve(s):
        if len(s) == n:
            print(''.join(s))
            exit()
        for c in '123':
            flag = True
            s.append(c)
            for i in range(1, len(s) // 2 + 1):
                if s[-i:] == s[-2 * i:-i]:
                    flag = False
                    break
            if flag:
                _solve(s)
            s.pop()

    _solve(['1'])


if __name__ == '__main__':
    n = int(input())
    solve(n)
