# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/13164
n, k = map(int, input().split())
arr = list(map(int, input().split()))
diif = []
for i in range(n - 1):
    diif.append(arr[i + 1] - arr[i])
diif.sort()
print(sum(diif[:n - k]))
