# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/15971
from sys import stdin

input = stdin.readline

n, root, leaf  = map(int, input().split())
if root == leaf:
    print(0)
    exit()
graph = [[] for _ in range(n + 1)]
for _ in range(n - 1):
    x, y, d = map(int, input().split())
    graph[x].append((y, d))
    graph[y].append((x, d))
dist = [0] * (n + 1)
maxEdge = [0] * (n + 1)
pts = [root]
for idx in pts:
    for adj, ex in graph[idx]:
        if adj != root and dist[adj] == 0:
            dist[adj] = dist[idx] + ex
            maxEdge[adj] = max(maxEdge[idx], ex)
            if adj == leaf:
                print(dist[adj] - maxEdge[adj])
                exit()
            pts.append(adj)
else:
    raise ValueError("No path from root to leaf")
