# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2632
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2632&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

t = int(input())
n, m = map(int, input().split())
a = [int(input()) for _ in range(n)]
b = [int(input()) for _ in range(m)]
for i in range(1, n):
    a[i] += a[i - 1]
for i in range(1, m):
    b[i] += b[i - 1]
ans = 0
memo = {}
memo[0] = 1
memo[a[-1]] = 1
for i in range(n):
    for j in range(n):
        if i != j:
            v = a[j] - a[i]
            if v < 0:
                v += a[-1]
            if i < j and v > t:
                break
            memo[v] = memo.get(v, 0) + 1
for i in range(m):
    for j in range(m):
        if i != j:
            v = b[j] - b[i]
            if v < 0:
                v += b[-1]
            if i < j and v > t:
                break
            ans += memo.get(t - v, 0)
ans += memo.get(t, 0)
ans += memo.get(t - b[-1], 0)
print(ans)

