# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/18405
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=18405&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, k = map(int, input().split())
board = [list(map(int, input().split())) for _ in range(n)]
s, r, c = map(int, input().split())
entry = [[] for _ in range(k + 1)]
for i in range(n):
    for j in range(n):
        if board[i][j] != 0:
            entry[board[i][j]].append((i, j))
dx = [0, 0, -1, 1]
dy = [-1, 1, 0, 0]
for _ in range(s):
    flag = False
    for idx in range(1, k + 1):
        new = []
        for x, y in entry[idx]:
            for d in range(4):
                nx = x + dx[d]
                ny = y + dy[d]
                if 0 <= nx < n and 0 <= ny < n and board[nx][ny] == 0:
                    flag = True
                    board[nx][ny] = idx
                    new.append((nx, ny))
        entry[idx] = new
    if not flag or board[r - 1][c - 1]:
        break
print(board[r - 1][c - 1])
