# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16929
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16929&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m = map(int, input().split())
board = [input() for _ in range(n)]
visited = [[False] * m for _ in range(n)]
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]
for i in range(n):
    for j in range(m):
        if visited[i][j]:
            continue
        ref = board[i][j]
        visited[i][j] = True
        que = [(-1, -1, i, j)]
        flag = False
        for px, py, x, y in que:
            for d in range(4):
                nx = x + dx[d]
                ny = y + dy[d]
                if 0 <= nx < n and 0 <= ny < m and board[nx][ny] == ref:
                    if visited[nx][ny]:
                        if px != nx or py != ny:
                            flag = True
                    else:
                        visited[nx][ny] = True
                        que.append((x, y, nx, ny))
        if flag:
            print('Yes')
            exit()
print('No')
