# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1891
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1891&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def to_point(ds):
    x = y = 0
    move = 2 ** (len(ds) - 1)
    for d in ds:
        if d == 1:
            x += move
            y += move
        elif d == 2:
            x -= move
            y += move
        elif d == 3:
            x -= move
            y -= move
        elif d == 4:
            x += move
            y -= move
        move //= 2
    return x, y


def from_point(x, y, n):
    ds = []
    move = 2 ** (n - 1)
    for _ in range(n):
        if x >= 0 and y >= 0:
            ds.append(1)
            x -= move
            y -= move
        elif x < 0 and y >= 0:
            ds.append(2)
            x += move
            y -= move
        elif x < 0 and y < 0:
            ds.append(3)
            x += move
            y += move
        elif x >= 0 and y < 0:
            ds.append(4)
            x -= move
            y += move
        move //= 2
    return ds


n, ds = input().split()
n = int(n)
ds = [int(d) for d in ds]
dx, dy = map(int, input().split())
px, py = to_point(ds)
px += dx * 2
py += dy * 2
if abs(px) > 2 ** n or abs(py) > 2 ** n:
    print(-1)
else:
    print(''.join(str(d) for d in from_point(px, py, n)))
