# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/11562
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=11562&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
import sys

input = sys.stdin.readline

n, m = map(int, input().split())
g = [[sys.maxsize] * (n+1) for _ in range(n+1)]
for _ in range(m):
    u, v, b = map(int, input().split())
    if b == 0: # 일방 통행
        g[u][v] = 0
        g[v][u] = 1
    elif b == 1:
        g[u][v] = g[v][u] = 0

for i in range(1, n+1):
    g[i][i] = 0

for p in range(1, n+1):
    for i in range(1, n+1):
        for j in range(1, n+1):
            g[i][j] = min(g[i][j], g[i][p] + g[p][j])

k = int(input())
for _ in range(k):
    s, e = map(int, input().split())
    print(g[s][e])
