# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/10473
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=10473&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
import heapq

input = stdin.readline
INF = 1e9


def dist(a, b):
    return ((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2) ** 0.5


def time(a, b, can_shoot=True):
    d = dist(a, b)
    t = d / 5
    if not can_shoot:
        return t
    if t < 2:
        return t
    if d < 50:
        return min(t, 2 + (50 - d) / 5)
    return min(t, 2 + (d - 50) / 5)


def dijkstra(start, end):
    dist = [INF] * len(graph)
    dist[start] = 0
    pq = [(0, start)]
    while pq:
        c, idx = heapq.heappop(pq)
        if dist[idx] < c:
            continue
        for adj, ex in graph[idx]:
            nd = c + ex
            if nd < dist[adj]:
                dist[adj] = nd
                heapq.heappush(pq, (nd, adj))
    return dist[end]


ix, iy = map(float, input().split())
init = (ix, iy)
fx, fy = map(float, input().split())
fin = (fx, fy)
n = int(input())
points = [tuple(map(float, input().split())) for _ in range(n)]
start = n
end = n + 1
graph = [[] for _ in range(n + 2)]
graph[start].append((end, time(init, fin, can_shoot=False)))
for i in range(n):
    p = points[i]
    graph[start].append((i, time(init, p, can_shoot=False)))
    graph[i].append((end, time(p, fin)))
for i in range(n):
    for j in range(i + 1, n):
        t = time(points[i], points[j])
        graph[i].append((j, t))
        graph[j].append((i, t))


print(dijkstra(start, end))
