# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1034
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1034&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m = map(int, input().split())
ans = 0
cnt = {}
for _ in range(n):
    line = input()
    cnt[line] = cnt.get(line, 0) + 1
ks = sorted(cnt.keys(), key=lambda x: cnt[x], reverse=True)
x = int(input())
for k in ks:
    v = cnt[k]
    t = 0
    for i in k:
        if i == '0':
            t += 1
    if t % 2 == x % 2 and t <= x:
        ans = v
        break
print(ans)
