# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16947
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16947&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def find(x):
    if parent[x] == x:
        return x
    parent[x] = find(parent[x])
    return parent[x]


n = int(input())
graph = [[] for _ in range(n + 1)]
parent = list(range(n + 1))
mx = my = 0
for _ in range(n):
    x, y = map(int, input().split())
    fx, fy = find(x), find(y)
    if fx != fy:
        parent[fy] = fx
        graph[x].append(y)
        graph[y].append(x)
    else:
        mx, my = x, y
pts = [mx]
parent = [0] * (n + 1)
for idx in pts:
    for adj in graph[idx]:
        if not parent[adj]:
            parent[adj] = idx
            pts.append(adj)
in_cycle = [0] * (n + 1)
in_cycle[mx] = 1
while my != mx:
    in_cycle[my] = 1
    my = parent[my]
ans = [0] * (n + 1)
for idx in range(1, n + 1):
    memo = idx
    while not in_cycle[idx]:
        ans[memo] += 1
        idx = parent[idx]
print(*ans[1:])
