# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16964
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16964&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def main():
    n = int(input())
    graph = [[] for _ in range(n + 1)]
    for _ in range(n - 1):
        x, y = map(int, input().split())
        graph[x].append(y)
        graph[y].append(x)
    arr = tuple(map(int, input().split()))
    mapper = {}
    for i, v in enumerate(arr):
        mapper[v] = i
    visited = [False] * (n + 1)
    visited[1] = True
    stack = [1]
    p = 0
    while stack:
        idx = stack.pop()
        visited[idx] = True
        if arr[p] != idx:
            return False
        p += 1
        tmp = []
        for adj in graph[idx]:
            if not visited[adj]:
                tmp.append(adj)
        tmp.sort(key=lambda x: mapper[x], reverse=True)
        stack += tmp
    return True


if __name__ == '__main__':
    print(int(main()))
