# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16920
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16920&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from collections import deque

input = stdin.readline


def main():
    n, m, p = map(int, input().split())
    speed = [0] + list(map(int, input().split()))
    board = [
        [int(v) if v.isdigit() else (0 if v == '.' else -1) for v in input().rstrip()]
        for _ in range(n)
    ]
    start_points = [[] for _ in range(p + 1)]
    cnt = [0] * (p + 1)
    for i in range(n):
        for j, v in enumerate(board[i]):
            if v > 0:
                start_points[v].append((i, j))
                cnt[v] += 1
    dx = [1, -1, 0, 0]
    dy = [0, 0, 1, -1]
    while True:
        any_progress = False
        for pt in range(1, p + 1):
            q = deque(start_points[pt])
            progressed = False
            for _ in range(speed[pt]):
                if not q:
                    break
                for _ in range(len(q)):
                    x, y = q.popleft()
                    for d in range(4):
                        nx = x + dx[d]
                        ny = y + dy[d]
                        if 0 <= nx < n and 0 <= ny < m and board[nx][ny] == 0:
                            board[nx][ny] = pt
                            q.append((nx, ny))
                            cnt[pt] += 1
                            progressed = True
            start_points[pt] = list(q)
            any_progress |= progressed
        if not any_progress:
            break
    print(*cnt[1:])


main()
