# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16118
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16118&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import heappop, heappush

input = stdin.readline
INF = float('inf')


def dijikstra(start, speed_arr=[1]):
    dist = [[INF] * len(speed_arr) for _ in range(n + 1)]
    dist[start][0] = 0
    pq = [(0, start, 0)]
    while pq:
        t, idx, s_idx = heappop(pq)
        if dist[idx][s_idx] < t:
            continue
        s = speed_arr[s_idx]
        s_adj = (s_idx + 1) % len(speed_arr)
        for adj, ex in graph[idx]:
            if dist[adj][s_adj] > (v := t + ex * s):
                dist[adj][s_adj] = v
                heappush(pq, (v, adj, s_adj))
    return [min(line) for line in dist]


n, m = map(int, input().split())
graph = [[] for _ in range(n + 1)]
for _ in range(m):
    x, y, d = map(int, input().split())
    graph[x].append((y, d))
    graph[y].append((x, d))
fox = dijikstra(1, [2])
wolf = dijikstra(1, [1, 4])
print(sum(fox[i] < wolf[i] for i in range(1, n + 1)))
