# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2617
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2617&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
connection = [[0] * (n + 1) for _ in range(n + 1)]
for _ in range(m):
    x, y = map(int, input().split())
    connection[x][y] = 1
for i in range(1, n + 1):
    for j in range(1, n + 1):
        for k in range(1, n + 1):
            if connection[j][i] and connection[i][k]:
                connection[j][k] = 1
ans = 0
for target in range(1, n + 1):
    total1 = 0
    total2 = 0
    for compare in range(1, n + 1):
        total1 += connection[target][compare]
        total2 += connection[compare][target]
    if total1 > n // 2 or total2 > n // 2:
        ans += 1
print(ans)
