# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/4179
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=4179&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
board = [input().strip() for _ in range(n)]
ix, iy = 0, 0
fire = []
for i in range(n):
    for j in range(m):
        if board[i][j] == "J":
            ix, iy = i, j
        elif board[i][j] == "F":
            fire.append((i, j))
visited = [[-1] * m for _ in range(n)]
fire_visited = [[-1] * m for _ in range(n)]
visited[ix][iy] = 0
for fx, fy in fire:
    fire_visited[fx][fy] = 0
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]
for fx, fy in fire:
    for i in range(4):
        nx, ny = fx + dx[i], fy + dy[i]
        if 0 <= nx < n and 0 <= ny < m and fire_visited[nx][ny] == -1 and board[nx][ny] != "#":
            fire_visited[nx][ny] = fire_visited[fx][fy] + 1
            fire.append((nx, ny))
q = [(ix, iy)]
for ix, iy in q:
    for i in range(4):
        nx, ny = ix + dx[i], iy + dy[i]
        if 0 <= nx < n and 0 <= ny < m and visited[nx][ny] == -1 and board[nx][ny] != "#":
            if fire_visited[nx][ny] == -1 or visited[ix][iy] + 1 < fire_visited[nx][ny]:
                visited[nx][ny] = visited[ix][iy] + 1
                q.append((nx, ny))
ans = float("inf")
for i in range(n):
    if visited[i][0] != -1:
        ans = min(ans, visited[i][0])
    if visited[i][m - 1] != -1:
        ans = min(ans, visited[i][m - 1])
for i in range(m):
    if visited[0][i] != -1:
        ans = min(ans, visited[0][i])
    if visited[n - 1][i] != -1:
        ans = min(ans, visited[n - 1][i])
print(ans + 1 if ans != float("inf") else "IMPOSSIBLE")
