# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1826
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1826&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import heappush, heappop

input = stdin.readline

n = int(input())
oils = [tuple(map(int, input().split())) for _ in range(n)]
end, x = map(int, input().split())
oils.sort()
oil_value_q = []
ans = 0
oil_p = 0
while x < end:
    while oil_p < n and oils[oil_p][0] <= x:
        heappush(oil_value_q, -oils[oil_p][1])
        oil_p += 1
    if not oil_value_q:
        ans = -1
        break
    ans += 1
    x += -heappop(oil_value_q)
print(ans)
