# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/7432
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=7432&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def print_mapper(m, depth=0):
    keys = sorted(m.keys())
    for key in keys:
        print(' ' * depth + key)
        print_mapper(m[key], depth + 1)


mapper = {}
n = int(input())
lines = [input().strip() for _ in range(n)]
for line in lines:
    dirs = line.split("\\")
    cur = mapper
    for d in dirs:
        if d not in cur:
            cur[d] = {}
        cur = cur[d]
print_mapper(mapper)
