# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/24230
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=24230&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
want = list(map(int, input().split()))
ans = int(want[0] != 0)
for _ in range(n - 1):
    x, y = map(int, input().split())
    ans += want[x - 1] != want[y - 1]
print(ans)
