# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1039
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1039&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def main():
    n, k = input().split()
    l = len(n)
    if l <= 1:
        return -1
    q = {n}
    for _ in range(int(k)):
        new = set()
        for idx in q:
            a = list(idx)
            for i in range(l):
                for j in range(i + 1, l):
                    a[i], a[j] = a[j], a[i]
                    if a[0] != '0':
                        new.add(''.join(a))
                    a[i], a[j] = a[j], a[i]
        q = new
    if not q:
        return -1
    return max(map(int, q))


if __name__ == "__main__":
    print(main())
