# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14658
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14658&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m, l, k = map(int, input().split())
xs = [0, n]
ys = [0, m]
stars = [tuple(map(int, input().split())) for _ in range(k)]
for x, y in stars:
    xs.append(x)
    ys.append(y)
ans = 0
for x in xs:
    for y in ys:
        tmp = 0
        for sx, sy in stars:
            if x <= sx <= x + l and y <= sy <= y + l:
                tmp += 1
        if tmp > ans:
            ans = tmp
print(k - ans)
