# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/20440
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=20440&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
ts = []
for i in range(n):
    s, e = map(int, input().split())
    ts.append((s, i))
    ts.append((e, i))
ts.sort()
ans = 0
ans_time = [0, 0]
cnt = 0
flag = [False] * n
p = 0
past_t = 0
while p < len(ts):
    t, i = ts[p]
    if cnt == ans and past_t == ans_time[1]:
        ans_time[1] = t
    while p < len(ts) and ts[p][0] == t:
        i = ts[p][1]
        if not flag[i]:
            cnt += 1
            flag[i] = True
        else:
            cnt -= 1
            flag[i] = False
        p += 1
    if cnt > ans:
        ans = cnt
        ans_time[0] = t
        ans_time[1] = t
    past_t = t
print(ans)
print(*ans_time)
