# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2187
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2187&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, a, b = map(int, input().split())
points = [list(map(int, input().split())) for _ in range(n)]
ans = 0
for i in range(n):
    ir, ic, iv = points[i]
    for j in range(i + 1, n):
        jr, jc, jv = points[j]
        if abs(ir - jr) < a and abs(ic - jc) < b:
            ans = max(ans, abs(iv - jv))
print(ans)
