# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1508
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1508&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m, k = map(int, input().split())
arr = list(map(int, input().split()))
left = 1
right = n
while left <= right:
    mid = (left + right) // 2
    loc = [False] * k
    loc[0] = True
    x = arr[0]
    cnt = m - 1
    for i in range(1, k):
        if cnt == 0:
            break
        if arr[i] - x >= mid:
            loc[i] = True
            x = arr[i]
            cnt -= 1
    if cnt == 0:
        ans_loc = "".join(['1' if v else '0' for v in loc])
        left = mid + 1
    else:
        right = mid - 1
print(ans_loc)
