# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16472
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16472&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
line = input()
left = right = 0
cnt = {line[0]: 1}
k = 1
left = 0
ans = 1
for right in range(1, len(line)):
    c = line[right]
    if c not in cnt:
        cnt[c] = 0
    if cnt[c] == 0:
        k += 1
    cnt[c] += 1
    while k > n:
        cnt[line[left]] -= 1
        if cnt[line[left]] == 0:
            k -= 1
        left += 1
    ans = max(ans, right - left + 1)
print(ans)
