# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/6443
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=6443&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def solve(target):
    def _solve(counter, s=""):
        if len(s) == len(target):
            result.append(s)
            return
        for k, v in counter.items():
            if v > 0:
                counter[k] -= 1
                _solve(counter, s + k)
                counter[k] += 1

    cnt = {}
    for c in target:
        cnt[c] = cnt.get(c, 0) + 1
    result = []
    _solve(cnt)
    result.sort()
    print("\n".join(result))


n = int(input())
lines = [input() for _ in range(n)]
for line in lines:
    solve(line)
