# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16935
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16935&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def rotate_1(arr):
    return arr[::-1]


def rotate_2(arr):
    return [line[::-1] for line in arr]


def rotate_3(arr):
    n = len(arr)
    m = len(arr[0])
    new_arr = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            new_arr[j][n - i - 1] = arr[i][j]
    return new_arr


def rotate_4(arr):
    return rotate_3(rotate_3(rotate_3(arr)))


def rotate_5(arr):
    n = len(arr)
    m = len(arr[0])
    new_arr = [[0] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            if i < n // 2 and j < m // 2:
                new_arr[i][j + m // 2] = arr[i][j]
            elif i < n // 2 and j >= m // 2:
                new_arr[i + n // 2][j] = arr[i][j]
            elif i >= n // 2 and j >= m // 2:
                new_arr[i][j - m // 2] = arr[i][j]
            elif i >= n // 2 and j < m // 2:
                new_arr[i - n // 2][j] = arr[i][j]
    return new_arr


def rotate_6(arr):
    return rotate_5(rotate_5(rotate_5(arr)))


n, m, r = map(int, input().split())
arr = [list(map(int, input().split())) for _ in range(n)]
orderMap = {
    "1": rotate_1,
    "2": rotate_2,
    "3": rotate_3,
    "4": rotate_4,
    "5": rotate_5,
    "6": rotate_6
}
for o in input().split():
    arr = orderMap[o](arr)
for line in arr:
    print(*line)
