# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/10423
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=10423&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def find(x):
    if parents[x] == x:
        return x
    parents[x] = find(parents[x])
    return parents[x]


n, m, k = map(int, input().split())
factory = set(map(int, input().split()))
edges = [tuple(map(int, input().split())) for _ in range(m)]
parents = list(range(n + 1))
edges.sort(key=lambda x: x[-1])
ans = 0
components = n
for x, y, d in edges:
    fx, fy = find(x), find(y)
    if fx != fy:
        if fx in factory and fy in factory:
            continue
        if fy in factory:
            fx, fy = fy, fx
        parents[fy] = fx
        components -= 1
        ans += d
    if components == k:
        break
print(ans)
