# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/5052
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=5052&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

for _ in range(int(input())):
    n = int(input())
    arr = [input().strip() for _ in range(n)]
    arr.sort()
    ans = 'YES'
    for i in range(1, n):
        if arr[i].startswith(arr[i - 1]):
            ans = 'NO'
            break
    print(ans)
