# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/3108
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=3108&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def find(idx):
    if idx == parents[idx]:
        return idx
    parents[idx] = find(parents[idx])
    return parents[idx]


n = int(input())
parents = list(range(n + 1))
sq = [(0, 0, 0, 0) for _ in range(n + 1)]
pu = 0
for i in range(1, n + 1):
    x1, y1, x2, y2 = map(int, input().split())
    pu += 1
    if not parents[0]:
        if y1 <= 0 <= y2 and not x1 * x2:
            parents[0] = i
            pu -= 1
        elif x1 <= 0 <= x2 and not y1 * y2:
            parents[0] = i
            pu -= 1
    for j in range(1, i):
        x3, y3, x4, y4 = sq[j]
        if x2 < x3 or y2 < y3 or x1 > x4 or y1 > y4:
            pass
        elif x1 < x3 < x4 < x2 and y1 < y3 < y4 < y2:
            pass
        elif x3 < x1 < x2 < x4 and y3 < y1 < y2 < y4:
            pass
        else:
            pj = find(j)
            if pj != i:
                parents[pj] = i
                pu -= 1
    sq[i] = (x1, y1, x2, y2)
print(pu)
