# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1662
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1662&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
word = input()
stack = []
for c in word:
    if c != ')':
        stack.append(c)
    else:
        tmp = []
        while stack[-1] != '(':
            tmp.append(stack.pop())
        stack.pop()
        k = int(stack.pop())
        stack += tmp[::-1] * k
print(len(stack))
