# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1520
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1520&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
board = [list(map(int, input().split())) for _ in range(n)]
dp = [[0] * m for _ in range(n)]
dp[0][0] = 1
stack = []
for x in range(n):
    for y in range(m):
        stack.append((board[x][y], x, y))
stack.sort(reverse=True)
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]
for v, x, y in stack:
    for d in range(4):
        nx = x + dx[d]
        ny = y + dy[d]
        if 0 <= nx < n and 0 <= ny < m and board[nx][ny] > board[x][y]:
            dp[x][y] += dp[nx][ny]
print(dp[-1][-1])
