# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/9205
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=9205&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

for _ in range(int(input())):
    n = int(input())
    arr = [tuple(map(int, input().split())) for _ in range(n + 2)]
    ini = 0
    fin = n + 1
    graph = [[] for _ in range(n + 2)]
    for i in range(n + 2):
        for j in range(i + 1, n + 2):
            if abs(arr[i][0] - arr[j][0]) + abs(arr[i][1] - arr[j][1]) <= 1000:
                graph[i].append(j)
                graph[j].append(i)
    visited = [False] * (n + 2)
    visited[ini] = True
    queue = [ini]
    for idx in queue:
        for adj in graph[idx]:
            if not visited[adj]:
                visited[adj] = True
                queue.append(adj)
    print("happy" if visited[fin] else "sad")
