# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/8983
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=8983&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m, l = map(int, input().split())
arr = list(map(int, input().split()))
mob = [tuple(map(int, input().split())) for _ in range(m)]

arr.append(float('inf'))
arr.append(-float('inf'))
arr.sort()
ans = 0
for x, y in mob:
    if y > l:
        continue
    ex = l - y
    left = 0
    right = n + 1
    flag = False
    while left < right and not flag:
        mid = (left + right) // 2
        if arr[mid] > x:
            right = mid
        else:
            left = mid + 1
        if x - ex <= arr[mid] <= x + ex:
            flag = True
    if flag:
        ans += 1
print(ans) 
