# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/20955
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=20955&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin, setrecursionlimit

setrecursionlimit(10 ** 6)
input = stdin.readline


def find(idx):
    if parents[idx] == idx:
        return idx
    parents[idx] = find(parents[idx])
    return parents[idx]


n, m = map(int, input().split())
parents = list(range(n + 1))
ans = n - 1
for _ in range(m):
    x, y = map(int, input().split())
    fx, fy = find(x), find(y)
    if fx != fy:
        parents[fy] = fx
        ans -= 1
    else:
        ans += 1
print(ans)
