# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/3107
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=3107&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
line = input()
if line.startswith(":"):
    line = "0000" + line
if line.endswith(":"):
    line = line + "0000"
a = line.split(":")
k = len(a)
ans = []
for c in a:
    if c == "":
        for i in range(8 - k + 1):
            ans.append("0000")
    else:
        ans.append(c.zfill(4))
print(":".join(ans))
