# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2668
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2668&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = [0] + [int(input()) for _ in range(n)]
ans = set()
for i in range(1, n + 1):
    if i in ans:
        continue
    visited = [False] * (n + 1)
    visited[i] = True
    q = [i]
    for idx in q:
        adj = arr[idx]
        if adj == i:
            ans |= set(q)
            break
        if not visited[adj]:
            visited[adj] = True
            q.append(adj)
print(len(ans))
print(*sorted(list(ans)), sep='\n')
