# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16724
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16724&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import setrecursionlimit

setrecursionlimit(10 ** 6)

def find(idx):
    if parents[idx] != idx:
        parents[idx] = find(parents[idx])
    return parents[idx]

n, m = map(int, input().split())
parents = list(range(n * m + 1))
board = [input() for _ in range(n)]
ans = n * m
for i in range(n):
    for j in range(m):
        idx = i * m + j + 1
        c = board[i][j]
        ni, nj = i, j
        if c == "U":
            di, dj = -1, 0
        elif c == "D":
            di, dj = 1, 0
        elif c == "L":
            di, dj = 0, -1
        else:
            di, dj = 0, 1
        ni += di
        nj += dj
        if 0 <= ni < n and 0 <= nj < m:
            adj = ni * m + nj + 1
            p1, p2 = find(idx), find(adj)
            if p1 != p2:
                parents[p1] = p2
                ans -= 1
print(ans)
