# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1915
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1915&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n, m = map(int, input().split())
board = [list(map(int, input())) for _ in range(n)]
prefix_sum = [[0] * (m + 1) for _ in range(n + 1)]
for i in range(1, n + 1):
    for j in range(1, m + 1):
        prefix_sum[i][j] = prefix_sum[i - 1][j] + prefix_sum[i][j - 1] - prefix_sum[i - 1][j - 1] + board[i - 1][j - 1]
ans = 0
for i in range(1, n + 1):
    for j in range(1, m + 1):
        for k in range(ans + 1, min(n, m) + 1):
            if i + k - 1 > n or j + k - 1 > m:
                break
            if prefix_sum[i + k - 1][j + k - 1] - prefix_sum[i - 1][j + k - 1] - prefix_sum[i + k - 1][j - 1] + prefix_sum[i - 1][j - 1] == k * k:
                ans = k
            else:
                break
print(ans * ans)
