# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1111
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1111&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
if n == 1:
    print("A")
    exit()
ans = set()
for a in range(-200, 201):
    b = arr[1] - a * arr[0]
    flag = True
    for i in range(1, n):
        if a * arr[i - 1] + b != arr[i]:
            flag = False
            break
    if flag:
        ans.add(a * arr[-1] + b)
if ans:
    print(ans.pop() if len(ans) == 1 else "A")
else:
    print("B")
