# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/20187
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=20187&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def right(board):
    new_board = []
    for line in board:
        new_board.append([i ^ 1 for i in line[::-1]] + line)
    return new_board


def left(board):
    new_board = []
    for line in board:
        new_board.append(line + [i ^ 1 for i in line[::-1]])
    return new_board


def up(board):
    new_board = []
    for line in board[::-1]:
        new_board.append([i ^ 2 for i in line])
    return board + new_board


def down(board):
    new_board = []
    for line in board[::-1]:
        new_board.append([i ^ 2 for i in line])
    return new_board + board


func_map = {
    "R": right,
    "L": left,
    "U": up,
    "D": down
}
n = int(input())
orders = list(input().split())[::-1]
board = [[int(input())]]
for o in orders:
    board = func_map[o](board)
for line in board:
    print(*line)
