# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1325
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
graph = [[] for _ in range(n + 1)]
for _ in range(m):
    a, b = map(int, input().split())
    graph[b].append(a)
t = 0
entry = []
for i in range(1, n + 1):
    visited = [False] * (n + 1)
    visited[i] = True
    queue = [i]
    tt = 1
    for idx in queue:
        for j in graph[idx]:
            if not visited[j]:
                visited[j] = True
                queue.append(j)
                tt += 1
    if tt > t:
        t = tt
        entry = [i]
    elif tt == t:
        entry.append(i)
print(*entry)
