# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16954
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16954&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from collections import defaultdict

board = [input() for _ in range(8)]
check = defaultdict(set)
for i in range(8):
    for j in range(8):
        if board[i][j] == '#':
            for k in range(8 - i):
                check[(i + k, j)].add(k)
                check[(i + k + 1, j)].add(k)
dx = [1, 1, 1, 0, 0, 0, -1, -1, -1]
dy = [1, 0, -1, 1, 0, -1, 1, 0, -1]
ans = 0
now = {(7, 0)}
for turn in range(8):
    new = set()
    for x, y in now:
        for d in range(9):
            nx = x + dx[d]
            ny = y + dy[d]
            if 0 <= nx < 8 and 0 <= ny < 8 and turn not in check[(nx, ny)]:
                new.add((nx, ny))
    now = new
    if not now:
        break
else:
    ans = 1
print(ans)
