# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/25401
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=25401&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
ans = n - 1
for i in range(n):
    for j in range(i + 1, n):
        dx = j - i
        dy = arr[j] - arr[i]
        if not dy % dx:
            a = dy // dx
            cnt = 0
            for k in range(n):
                if arr[k] == arr[i] + a * (k - i):
                    cnt += 1
            ans = min(ans, n - cnt)
print(ans)
