# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2800
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2800&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
line = input()
stack = []
bracket = []
for i in range(len(line)):
    if line[i] == '(':
        stack.append(i)
    elif line[i] == ')':
        bracket.append((stack.pop(), i))
t = len(bracket)
ans = []
for checker in range(1, 1 << t):
    temp = list(line)
    for bit in range(t):
        if (1 << bit) & checker:
            temp[bracket[bit][0]] = ''
            temp[bracket[bit][1]] = ''
    ans.append(''.join(temp))
ans = sorted(list(set(ans)))
print('\n'.join(ans))
