# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14867
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14867&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from math import gcd

input = stdin.readline

a, b, c, d = map(int, input().split())
g = gcd(a, b)
if c % g or d % g:
    print(-1)
    exit()
a //= g
b //= g
c //= g
d //= g
visited = set()
q = [(0, 0)]
visited.add((0, 0))
t = 0
while q and (c, d) not in visited:
    new = []
    t += 1
    for x, y in q:
        if (a, y) not in visited:
            visited.add((a, y))
            new.append((a, y))
        if (x, b) not in visited:
            visited.add((x, b))
            new.append((x, b))
        if (0, y) not in visited:
            visited.add((0, y))
            new.append((0, y))
        if (x, 0) not in visited:
            visited.add((x, 0))
            new.append((x, 0))
        if x + y <= b and (0, x + y) not in visited:
            visited.add((0, x + y))
            new.append((0, x + y))
        if x + y > b and (x + y - b, b) not in visited:
            visited.add((x + y - b, b))
            new.append((x + y - b, b))
        if x + y <= a and (x + y, 0) not in visited:
            visited.add((x + y, 0))
            new.append((x + y, 0))
        if x + y > a and (a, x + y - a) not in visited:
            visited.add((a, x + y - a))
            new.append((a, x + y - a))
    q = new
if (c, d) not in visited:
    print(-1)
else:
    print(t)
