# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/6198
from sys import stdin

input = stdin.readline

stack = []
ans = 0
for _ in range(int(input())):
    h = int(input())
    while stack and stack[-1] <= h:
        stack.pop()
    ans += len(stack)
    stack.append(h)
print(ans)
