"""
Make your study record automatically!
This script will generate files from your README.md.
You can find hints by --help option.
For now, this script only supports BOJ with python.
"""
import sys
import os
import argparse

mapper = {
    "백준": "BOJ",
    "프로그래머스": "PGS",
    "삼성 SW 역량 테스트": "SWT",
}
parser = argparse.ArgumentParser()
parser.add_argument("--date", type=str, help="target date, YYYYMMDD")
parser.add_argument("--user", type=str, help="user ID, maybe your github ID")
args = parser.parse_args()

def main():
    if (date := args.date) is None:
        print("date is required!", flush=True)
        date = input("date? (YYYYMMDD) ex. 20230102")
    if (userID := args.user) is None:
        print("user ID is required!", flush=True)
        userID = input("user ID? (maybe your github ID) ex. bomul1128")
    try:
        sys.stdin = open(f"{date}/README.md", "r")
    except FileNotFoundError:
        print(f"README.md at {date} not found!", flush=True)
        return
    while True:
        try:
            line = input()
            try:
                _, raw, *_ = line.split('[')
                name, *_ = raw.split(']')
            except ValueError:
                continue
            rawPlatform, idx, *rawTitle = name.split()
            title = ''.join(rawTitle)
            platform = mapper.get(rawPlatform, "UNKNOWN")
            filename = f"{date}/{userID}/[{platform}]_{idx}_{title}.py"
            os.makedirs(os.path.dirname(filename), exist_ok=True)
            with open(filename, "w") as f:
                f.write(f"# Generated by make_my_study_record.py\n")
                f.write(f"# BOJ LINK : https://www.acmicpc.net/problem/{idx}\n")
                f.close()
        except EOFError:
            break
    print(f"Files generated successfully!", flush=True)
    return


if __name__ == "__main__":
    main()
