# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/7682
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=7682&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
bingos = [
    (0, 1, 2), (3, 4, 5), (6, 7, 8),  # rows
    (0, 3, 6), (1, 4, 7), (2, 5, 8),  # columns
    (0, 4, 8), (2, 4, 6)              # diagonals
]

def check(s):
    def has_line(c):
        return any(all(s[i] == c for i in line) for line in bingos)

    x_count = s.count('X')
    o_count = s.count('O')
    if x_count < o_count or x_count > o_count + 1:
        return False
    x_bingo = has_line('X')
    o_bingo = has_line('O')
    if x_bingo and o_bingo:
        return False
    if not x_bingo and not o_bingo:
        return x_count + o_count == 9
    if x_bingo:
        return x_count == o_count + 1
    if o_bingo:
        return x_count == o_count
    return False


while True:
    line = input()
    if line == 'end':
        break
    print('valid' if check(line) else 'invalid')
