# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/9576
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=9576&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def main():
    def find(x):
        if parents[x] != x:
            parents[x] = find(parents[x])
        return parents[x]

    n, m = map(int, input().split())
    books = [tuple(map(int, input().split())) for _ in range(m)]
    books.sort(key=lambda x: x[1])
    used = [False] * (n + m + 1)
    parents = list(range(n + m + 1))
    ans = 0
    for s, e in books:
        root_s = find(s)
        if root_s <= e:
            used[root_s] = True
            parents[root_s] = root_s + 1
            ans += 1
    print(ans)


for _ in range(int(input())):
    main()
