# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14921
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14921&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
x = 0
y = n - 1
ans = arr[0] + arr[-1]
while x < y:
    tmp = arr[x] + arr[y]
    if abs(tmp) < abs(ans):
        ans = tmp
    if tmp < 0:
        x += 1
    else:
        y -= 1
print(ans)
