# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2531
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2531&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, d, k, c = map(int, input().split())
sushi = [int(input()) for _ in range(n)]
counter = [0] * (d + 1)
num = 0
for i in range(k):
    if counter[sushi[i]] == 0:
        num += 1
    counter[sushi[i]] += 1
ans = num
for i in range(n):
    if counter[sushi[i]] == 1:
        num -= 1
    counter[sushi[i]] -= 1

    if counter[sushi[(i + k) % n]] == 0:
        num += 1
    counter[sushi[(i + k) % n]] += 1
    ans = max(ans, num + (counter[c] == 0))
print(ans)
