# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1726
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1726&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
board = [list(map(int, input().split())) for _ in range(n)]
rx, ry, rd = map(int, input().split())
rx -= 1
ry -= 1
rd -= 1
fx, fy, fd = map(int, input().split())
fx -= 1
fy -= 1
fd -= 1
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]
ddd = {
    0: [2, 3],
    1: [2, 3],
    2: [0, 1],
    3: [0, 1],
}
visited = {(rx, ry, rd): 0}
q = [(rx, ry, rd)]
for x, y, d in q:
    if (x, y, d) == (fx, fy, fd):
        break
    v = visited[(x, y, d)]
    for i in range(1, 4):
        nx, ny = x + dx[d] * i, y + dy[d] * i
        if nx < 0 or nx >= n or ny < 0 or ny >= m or board[nx][ny] == 1:
            break
        if (nx, ny, d) in visited:
            continue
        visited[(nx, ny, d)] = v + 1
        q.append((nx, ny, d))
    for nd in ddd[d]:
        if (x, y, nd) in visited:
            continue
        visited[(x, y, nd)] = v + 1
        q.append((x, y, nd))
print(visited.get((fx, fy, fd), -1))
