# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2836
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2836&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
target = []
for i in range(n):
    x, y = map(int, input().split())
    if x > y:
        target.append((y, x))
target.sort()
ans = m
l = 0
r = 0
for x, y in target:
    if r < x:
        ans += (r - l) * 2
        l = x
        r = y
    elif x <= r < y:
        r = y
ans += (r - l) * 2
print(ans)
