# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/15732
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=15732&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def main():
    def check(rule, v):
        a, b, c = rule
        if v < a:
            return 0
        if b <= v:
            return (b - a) // c + 1
        return (v - a) // c + 1


    n, k, d = map(int, input().split())
    rules = [tuple(map(int, input().split())) for _ in range(k)]
    left = 1
    right = n
    ans = -1
    while left <= right:
        mid = (left + right) // 2
        tmp = sum(check(rule, mid) for rule in rules)
        if tmp >= d:
            ans = mid
            right = mid - 1
        else:
            left = mid + 1
    print(ans)


if __name__ == '__main__':
    main()
