# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/15661
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=15661&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
board = [list(map(int, input().split())) for _ in range(n)]
team_score = [0] * (1 << n)
for b in range(n):
    bit = 1 << b
    for idx in range(bit):
        team_score[idx | bit] = team_score[idx]
        for c in range(b):
            if (idx >> c) & 1:
                team_score[idx | bit] += board[b][c]
                team_score[idx | bit] += board[c][b]
ans = float('inf')
for t1 in range(1 << n):
    t2 = (1 << n) - 1 - t1
    tmp = abs(team_score[t1] - team_score[t2])
    if ans > tmp:
        ans = tmp
print(ans)
