# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/4716
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=4716&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
# WRONG ANSWER
from sys import stdin

input = stdin.readline


def main(n, a, b):
    # k, da, db
    board = [tuple(map(int, input().split())) for _ in range(n)]
    tmp = 0
    s = []
    ta = tb = 0
    for k, da, db in board:
        tmp += k * da
        ta += k
        s.append((da - db, k))
    ans = float("inf")
    s.sort()
    while s:
        diff, k = s.pop()
        if diff <= 0 and ta <= a:
            break
        use = min(k, b - tb)
        tmp -= use * diff
        if ta <= a and tb <= b:
            ans = min(ans, tmp)
        tb += use
        ta -= use
    print(ans)


if __name__ == "__main__":
    while True:
        n, a, b = map(int, input().split())
        if n == a == b == 0:
            break
        main(n, a, b)
