# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/15926
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=15926&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
line = input()
ans = 0
stack = []
mapper = {}
for i, c in enumerate(line):
    if c == '(':
        stack.append(i)
    elif stack:
        j = stack.pop()
        if j - 1 in mapper:
            k = mapper[j - 1]
        else:
            k = j
        mapper[i] = k
        tmp = i - k + 1
        if tmp > ans:
            ans = tmp
print(ans)
