# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/9466
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=9466&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

for _ in range(int(input())):
    n = int(input())
    arr = [0] + list(map(int, input().split()))
    root = [0] * (n + 1)
    depth = [0] * (n + 1)
    ans = n
    for i in range(1, n + 1):
        if not depth[i]:
            s = i
            root[i] = s
            depth[i] = 1
            while not depth[arr[i]]:
                depth[arr[i]] = depth[i] + 1
                root[arr[i]] = s
                i = arr[i]
            if root[i] == root[arr[i]]:
                ans -= depth[i] - depth[arr[i]] + 1
    print(ans)
