# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/25381
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=25381&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
line = input()
a = []
b = []
ans = bp = 0
for i in range(len(line)):
    if line[i] == 'A':
        a.append(i)
    elif line[i] == 'B':
        b.append(i)
    elif bp < len(b):
        bp += 1
        ans += 1
for ai in a:
    while bp < len(b) and b[bp] < ai:
        bp += 1
    if bp < len(b):
        ans += 1
        bp += 1
    if bp >= len(b):
        break
print(ans)
