# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1245
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1245&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def search(ix, iy):
    if visited[ix][iy] or board[ix][iy] == 0:
        return False
    visited[ix][iy] = True
    q = [(ix, iy)]
    v = board[ix][iy]
    flag = True
    for x, y in q:
        for d in range(8):
            nx, ny = x + dx[d], y + dy[d]
            if 0 <= nx < n and 0 <= ny < m:
                nv = board[nx][ny]
                if v == nv:
                    if not visited[nx][ny]:
                        q.append((nx, ny))
                        visited[nx][ny] = True
                elif nv > v:
                    flag = False
    return flag

dx = [0, 0, 1, -1, 1, 1, -1, -1]
dy = [1, -1, 0, 0, 1, -1, 1, -1]
n, m = map(int, input().split())
board = [list(map(int, input().split())) for _ in range(n)]
visited = [[False] * m for _ in range(n)]
ans = 0
for i in range(n):
    for j in range(m):
        if not visited[i][j] and board[i][j]:
            ans += search(i, j)
print(ans)
