# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/14923
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=14923&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
sx, sy = map(int, input().split())
ex, ey = map(int, input().split())
sx -= 1
sy -= 1
ex -= 1
ey -= 1
board = [list(map(int, input().split())) for _ in range(n)]
dist = [[[-1, -1] for _ in range(m)] for _ in range(n)]
dist[sx][sy] = [0, 0]
q = [(sx, sy, 0)]
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]
for x, y, magic in q:
    cost = dist[x][y][magic]
    for d in range(4):
        nx = x + dx[d]
        ny = y + dy[d]
        if 0 <= nx < n and 0 <= ny < m:
            if board[nx][ny] == 0:
                if dist[nx][ny][magic] == -1:
                    dist[nx][ny][magic] = cost + 1
                    q.append((nx, ny, magic))
            else:
                if magic == 0 and dist[nx][ny][1] == -1:
                    dist[nx][ny][1] = cost + 1
                    q.append((nx, ny, 1))
a, b = dist[ex][ey]
if a == b == -1:
    print(-1)
elif a == -1:
    print(b)
elif b == -1:
    print(a)
else:
    print(min(a, b))
