# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/4195
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=4195&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def register(name):
    if not parents.get(name):
        parents[name] = name
        nums[name] = 1
    return


def find(target):
    if parents[target] == target:
        return target
    parents[target] = find(parents[target])
    return parents[target]


def union(a, b):
    x = find(a)
    y = find(b)
    if x != y:
        parents[y] = x
        nums[x] += nums[y]
    return nums[x]


for _ in range(int(input())):
    n = int(input())
    parents = {}
    nums = {}
    for _ in range(n):
        p1, p2 = input().rstrip().split()
        register(p1)
        register(p2)
        print(union(p1, p2))
