# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2109
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2109&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import *

input = stdin.readline

n = int(input())
v = [tuple(map(int, input().split())) for _ in range(n)]
v.sort(key=lambda x: (x[1], x[0]))
ans = 0
pq = []
past = -1
while v:
    x, d = v.pop()
    while pq and past > d:
        ans -= heappop(pq)
        past -= 1
    heappush(pq, -x)
    while v and v[-1][1] == d:
        x, _ = v.pop()
        heappush(pq, -x)
    past = d
while pq and past > 0:
    ans -= heappop(pq)
    past -= 1
print(ans)
