# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1240
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1240&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
edges = [tuple(map(int, input().split())) for _ in range(n - 1)]
INF = 10 ** 9
dist = [[INF] * (n + 1) for _ in range(n + 1)]
for i in range(1, n + 1):
    dist[i][i] = 0
graph = [[] for _ in range(n + 1)]
for u, v, d in edges:
    graph[u].append((v, d))
    graph[v].append((u, d))
for _ in range(m):
    u, v = map(int, input().split())
    visited = [False] * (n + 1)
    visited[u] = True
    q = [u]
    for x in q:
        if x == v:
            break
        for y, d in graph[x]:
            if not visited[y]:
                visited[y] = True
                dist[u][y] = dist[u][x] + d
                dist[y][u] = dist[u][y]
                q.append(y)
    print(dist[u][v])
