# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/3780
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=3780&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin, setrecursionlimit

input = stdin.readline
setrecursionlimit(10 ** 5)


def main():
    def find(idx):
        if idx == parents[idx]:
            return idx, 0
        adj, d = find(parents[idx])
        parents[idx] = adj
        dist[idx] += d
        return adj, dist[idx]

    n = int(input())
    parents = list(range(n + 1))
    dist = [0] * (n + 1)
    while True:
        q, *vs = input().split()
        if q == 'O':
            return
        if q == 'E':
            idx, *_ = map(int, vs)
            _, d = find(idx)
            print(d)
        elif q == 'I': 
            idx, adj, *_ = map(int, vs)
            parents[idx] = adj
            dist[idx] = abs(idx - adj) % 1000


if __name__ == "__main__":
    for _ in range(int(input())):
        main()
