# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2310
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2310&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from collections import deque


def main(n):
    rooms = [0] * (n + 1)
    graph = [[] for _ in range(n + 1)]
    graph[0].append(1)
    for idx in range(1, n + 1):
        c, v, *adjs = input().split()
        if c == 'E':
            v = 0
        elif c == 'L':
            v = int(v)
        else:
            v = -int(v)
        rooms[idx] = v
        for adj in adjs:
            graph[idx].append(int(adj))
    visited = [[False] * 501 for _ in range(n + 1)]
    queue = deque([(0, 0)])
    while queue:
        idx, money = queue.popleft()
        if idx == n:
            print("Yes")
            return
        for adj in graph[idx]:
            val = rooms[adj]
            if val > 0:
                if val > money:
                    money = val
            elif val < 0:
                money += val
                if money < 0:
                    continue
            if not visited[adj][money]:
                visited[adj][money] = True
                queue.append((adj, money))
    print("No")
    return


if __name__ == "__main__":
    while n := int(input()):
        main(n)
