# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/3079
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=3079&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
arr = [int(input()) for _ in range(n)]
ans = 0
left = 1
right = max(arr) * m
while left <= right:
    mid = (left + right) // 2
    cnt = 0
    for i in arr:
        cnt += mid // i
    if cnt >= m:
        ans = mid
        right = mid - 1
    else:
        left = mid + 1
print(ans)
