# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2493
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2493&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
tower = list(map(int, input().split()))
ans = [0] * n
stack = [(10 ** 8 + 1, 0)]
for i in range(n):
    h = tower[i]
    while stack[-1][0] < h:
        stack.pop()
    ans[i] = stack[-1][1]
    stack.append((h, i + 1))
print(*ans)
