# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16637
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16637&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def evaluate(v1, o1, v2):
    if o1 == '+':
        return v1 + v2
    elif o1 == '-':
        return v1 - v2
    return v1 * v2

n = int(input())
if n == 1:
    print(input())
    exit()
expr = input()
k = n // 2
prepre = [int(expr[0])]
pre = [evaluate(int(expr[0]), expr[1], int(expr[2]))]
for i in range(2, k + 1):
    entry = []
    o1, v1, o2, v2 = expr[2 * i - 3:2 * i + 1]
    v1, v2 = int(v1), int(v2)
    for e in pre:
        entry.append(evaluate(e, o2, v2))
    t = evaluate(v1, o2, v2)
    for e in prepre:
        entry.append(evaluate(e, o1, t))
    prepre = pre
    pre = entry
print(max(pre))
