# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17299
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17299&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
cnt = {}
for v in arr:
    cnt[v] = cnt.get(v, 0) + 1
ans = [0] * n
ans[-1] = -1
stack = []
for i in range(n - 1, -1, -1):
    while stack and cnt[stack[-1]] <= cnt[arr[i]]:
        stack.pop()
    ans[i] = stack[-1] if stack else -1
    stack.append(arr[i])
print(*ans)
