# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17140
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17140&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
r, c, k = map(int, input().split())
board = [list(map(int, input().split())) for _ in range(3)]
for t in range(101):
    if r - 1 < len(board) and c - 1 < len(board[0]) and board[r - 1][c - 1] == k:
        print(t)
        break
    if len(board) >= len(board[0]):
        new_board = []
        for row in board:
            count = {}
            for num in row:
                if num == 0:
                    continue
                count[num] = count.get(num, 0) + 1
            sorted_count = sorted(count.items(), key=lambda x: (x[1], x[0]))
            new_row = []
            for num, cnt in sorted_count:
                new_row += [num, cnt]
            new_board.append(new_row)
        max_len = max(len(row) for row in new_board)
        for row in new_board:
            row.extend([0] * (max_len - len(row)))
        board = new_board
    else:
        new_board = []
        for col_idx in range(len(board[0])):
            count = {}
            for row_idx in range(len(board)):
                num = board[row_idx][col_idx]
                if num == 0:
                    continue
                if num in count:
                    count[num] += 1
                else:
                    count[num] = 1
            sorted_count = sorted(count.items(), key=lambda x: (x[1], x[0]))
            new_col = []
            for num, cnt in sorted_count:
                new_col.extend([num, cnt])
            new_board.append(new_col)
        max_len = max(len(col) for col in new_board)
        for col in new_board:
            col += [0] * (max_len - len(col))
        board = [list(row) for row in zip(*new_board)]
else:
    print(-1)
