# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/5214
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=5214&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from collections import deque

input = stdin.readline

n, k, m = map(int, input().split())
stations = [list(map(int, input().split())) for _ in range(m)]
station_info = [[] for _ in range(n + 1)]
for i, s in enumerate(stations):
    for j in s:
        station_info[j].append(i)
visited = [False] * m
dist = [-1] * (n + 1)
dist[1] = 0
q = deque([1])
while q:
    idx = q.popleft()
    if idx == n:
        print(dist[idx] + 1)
        break
    for station in station_info[idx]:
        if visited[station]:
            continue
        visited[station] = True
        for next_idx in stations[station]:
            if dist[next_idx] == -1:
                dist[next_idx] = dist[idx] + 1
                q.append(next_idx)
else:
    print(-1)
