# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1507
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1507&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def main():
    n = int(input())
    board = [list(map(int, input().split())) for _ in range(n)]
    for j in range(n):
        for i in range(n):
            for k in range(n):
                a = board[i][j]
                b = board[j][k]
                c = board[i][k]
                if any(x == 0 for x in (a, b, c)):
                    continue
                if a + b == c:
                    board[i][k] = 0
                elif a + b < c:
                    print(-1)
                    return
    print(sum(sum(row) for row in board) // 2)


if __name__ == "__main__":
    main()
