# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16985
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16985&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from itertools import permutations


def main():
    def floor():
        return [list(map(int, input().split())) for _ in range(5)]

    def rotate(board):
        return [list(reversed(col)) for col in zip(*board)]
    
    def check(cube):
        if cube[0][0][0] == 0 or cube[4][4][4] == 0:
            return -1
        visited = [[[-1] * 5 for _ in range(5)] for _ in range(5)]
        dx = [1, -1, 0, 0, 0, 0]
        dy = [0, 0, 1, -1, 0, 0]
        dz = [0, 0, 0, 0, 1, -1]
        visited[0][0][0] = 0
        queue = [(0, 0, 0)]
        for x, y, z in queue:
            for d in range(6):
                nx = x + dx[d]
                ny = y + dy[d]
                nz = z + dz[d]
                if 0 <= nx < 5 and 0 <= ny < 5 and 0 <= nz < 5:
                    if cube[nx][ny][nz] == 1 and visited[nx][ny][nz] == -1:
                        if nx == ny == nz == 4:
                            return visited[x][y][z] + 1
                        visited[nx][ny][nz] = visited[x][y][z] + 1
                        queue.append((nx, ny, nz))
        return -1

    _cube = [floor() for _ in range(5)]
    rotated = []
    for f in _cube:
        c = [f]
        for _ in range(3):
            c.append(rotate(c[-1]))
        rotated.append(c)
    perms = list(permutations(range(5)))
    ans = -1
    for perm in perms:
        for b in range(1 << 10):
            cube = []
            for f in range(5):
                r = b % 4
                b //= 4
                cube.append(rotated[perm[f]][r])
            res = check(cube)
            if res != -1 and (ans == -1 or res < ans):
                ans = res
                if ans == 12:
                    print(ans)
                    return
    print(ans)


if __name__ == "__main__":
    main()
