# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/13144
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=13144&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
last = {}
ans = 0
left = 0
for i, v in enumerate(arr):
    if v in last and last[v] >= left:
        left = last[v] + 1
    last[v] = i
    ans += i - left + 1
print(ans)
