# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/32069
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=32069&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdout

def print(v):
    stdout.write(str(v) + "\n")



def main():
    L, n, k = map(int, input().split())
    raw = list(map(int, input().split()))
    pts = []
    for r in raw:
        if k > 0:
            print(0)
            k -= 1
        if not pts:
            pts.append([r, r])
            continue
        elif pts[-1][1] + 1 == r:
            pts[-1][1] = r
        else:
            pts.append([r, r])

    tmp = 1
    while k > 0:
        new = []
        for l, r in pts:
            if (new and new[-1][1] < l - 1) or (not new and l > 0):
                l -= 1
                k -= 1
                if k >= 0:
                    print(tmp)
            if r + 1 <= L:
                r += 1
                k -= 1
                if k >= 0:
                    print(tmp)
            if new and new[-1][1] + 1 == l:
                new[-1][1] = r
            else:
                new.append([l, r])
        tmp += 1
        pts = new


main()
