# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2933
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2933&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def throw(h, reverse=False):
    r = range(m) if not reverse else range(m - 1, -1, -1)
    for j in r:
        if board[h][j]:
            board[h][j] = False
            return j
    return -1


def drop(x, y):
    dx = [1, -1, 0, 0]
    dy = [0, 0, 1, -1]
    for d in range(4):
        nx = x + dx[d]
        ny = y + dy[d]
        if 0 <= nx < n and 0 <= ny < m and board[nx][ny]:
            visited = [[False] * m for _ in range(n + 1)]
            visited[nx][ny] = True
            cluster = [(nx, ny)]
            for cx, cy in cluster:
                for dd in range(4):
                    nnx = cx + dx[dd]
                    nny = cy + dy[dd]
                    if 0 <= nnx < n + 1 and 0 <= nny < m and board[nnx][nny] and not visited[nnx][nny]:
                        visited[nnx][nny] = True
                        cluster.append((nnx, nny))
            min_drop = n
            for cx, cy in cluster:
                drop_dist = 0
                for tx in range(cx + 1, n + 1):
                    if board[tx][cy] and not visited[tx][cy]:
                        break
                    drop_dist += 1
                min_drop = min(min_drop, drop_dist)
            if min_drop > 0:
                for cx, cy in cluster:
                    board[cx][cy] = False
                for cx, cy in cluster:
                    board[cx + min_drop][cy] = True


n, m = map(int, input().split())
board = [[s == 'x' for s in input().strip()] for _ in range(n)]
board.append([True] * m)
q = int(input())
qs = list(map(int, input().split()))
flag = False
for q in qs:
    x = n - q
    y = throw(x, reverse=flag)
    flag = not flag
    if y == -1:
        continue
    drop(x, y)
for i in range(n):
    print(''.join(['x' if board[i][j] else '.' for j in range(m)]))
