# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/9470
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=9470&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def main():
    k, n, m = map(int, input().split())
    graph = [[] for _ in range(n + 1)]
    order = [0] * (n + 1)
    cnt = [0] * (n + 1)
    max_parent = [0] * (n + 1)
    deg = [0] * (n + 1)
    for _ in range(m):
        x, y = map(int, input().split())
        graph[x].append(y)
        deg[y] += 1
    q = []
    for i in range(1, n + 1):
        if deg[i] == 0:
            q.append(i)
            order[i] = 1
    for idx in q:
        v = order[idx]
        for adj in graph[idx]:
            deg[adj] -= 1
            if max_parent[adj] < v:
                max_parent[adj] = v
                cnt[adj] = 1
            elif max_parent[adj] == v:
                cnt[adj] += 1
            if deg[adj] == 0:
                order[adj] = max_parent[adj] + (cnt[adj] > 1)
                q.append(adj)
    print(k, max(order))


if __name__ == "__main__":
    for _ in range(int(input())):
        main()
