# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2461
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2461&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
vals = [tuple(map(int, input().split())) for _ in range(n)]
arr = []
for i, val in enumerate(vals):
    for v in val:
        arr.append((v, i))
arr.sort()
cnt = [0] * n
in_stack = 0
left = 0
ans = float('inf')
for right, (val, idx) in enumerate(arr):
    if not cnt[idx]:
        in_stack += 1
    cnt[idx] += 1
    if in_stack == n:
        while cnt[arr[left][1]] > 1:
            cnt[arr[left][1]] -= 1
            left += 1
        ans = min(ans, val - arr[left][0])
print(ans)
