# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17619
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17619&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def find(target):
    if parents[target] == target:
        return target
    parents[target] = find(parents[target])
    return parents[target]


n, m = map(int, input().split())
intervals = []
for i in range(n):
    init, fin, _ = map(int, input().split())
    intervals.append((init, fin, i + 1))
queries = [tuple(map(int, input().split())) for _ in range(m)]
parents = list(range(n + 1))

intervals.sort()
last_init, last_fin, last_idx = intervals[0]
for init, fin, idx in intervals[1:]:
    if init <= last_fin:
        parents[idx] = last_idx
        last_fin = max(last_fin, fin)
    else:
        last_init, last_fin, last_idx = init, fin, idx

for idx, adj in queries:
    print(1 if find(idx) == find(adj) else 0)
