# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1113
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1113&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]
n, m = map(int, input().split())
board = [list(map(int, input().strip())) for _ in range(n)]
ans = 0
for h in range(9, 0, -1):
    visited = [[False] * m for _ in range(n)]
    for i in range(1, n - 1):
        for j in range(1, m - 1):
            if board[i][j] < h and not visited[i][j]:
                flag = True
                point = [(i, j)]
                visited[i][j] = True
                memo = [(i, j)]
                while point:
                    x, y = point.pop()
                    for d in range(4):
                        nx = x + dx[d]
                        ny = y + dy[d]
                        if 0 < nx < n - 1 and 0 < ny < m - 1:
                            if board[nx][ny] < h and not visited[nx][ny]:
                                visited[nx][ny] = True
                                point.append((nx, ny))
                                memo.append((nx, ny))
                        else:
                            if board[nx][ny] < h:
                                flag = False
                                visited[nx][ny] = True
                if flag:
                    for x, y in memo:
                        ans += h - board[x][y]
                        board[x][y] = h
print(ans)
