# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/24552
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=24552&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
a = input()
n = len(a)
l = a.count('(')
r = n - l
stack = 0
s = '('
if l >= r:
    a = a[::-1]
    s = ')'
for i in range(n):
    if a[i] == s:
        stack += 1
    elif stack:
        stack -= 1
    else:
        break
print(i // 2 + 1)
