# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/21608
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=21608&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
