# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1911
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1911&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, l = map(int, input().split())
arr = [list(map(int, input().split())) for _ in range(n)]
arr.sort()
ans = 0
start = 0
for x, y in arr:
    if start >= y:
        continue
    elif start <= x:
        tmp = (y - x) // l + ((y - x) % l != 0)
        start = x + tmp * l
        ans += tmp
    else:
        tmp = (y - start) // l + ((y - start) % l != 0)
        start += tmp * l
        ans += tmp
print(ans)
