# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2258
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2258&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
arr = []
for _ in range(n):
    x, y = map(int, input().split())
    arr.append((x, y))
arr.sort(key=lambda x: (x[1], -x[0]))
have = 0
past = 0
used = 0
ans = -1
for mass, price in arr:
    have += mass
    if past < price:
        used = price
        past = price
    elif past == price:
        used += price
    if have >= m:
        if ans == -1 or ans > used:
            ans = used
    if ans != -1 and price >= ans:
        break
print(ans)
