# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/20529
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=20529&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
for _ in range(n):
    m = int(input())
    ls = input().strip().split()
    if m >= 33:
        print(0)
        continue
    ans = float('inf')
    for i in range(m):
        for j in range(i + 1, m):
            for k in range(j + 1, m):
                tmp = 0
                for d in range(4):
                    if ls[i][d] != ls[j][d]:
                        tmp += 1
                    if ls[i][d] != ls[k][d]:
                        tmp += 1
                    if ls[j][d] != ls[k][d]:
                        tmp += 1
                ans = min(ans, tmp)
    print(ans)
