# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/25556
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=25556&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
n = int(input())
arr = list(map(int, input().split()))
for _ in range(4):
    if not arr:
        break
    u = arr[0]
    remain = []
    for v in arr[1:]:
        if v > u:
            u = v
        else:
            remain.append(v)
    arr = remain
print("YES" if not arr else "NO")
