# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2252
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2252&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n, m = map(int, input().split())
graph = [[] for _ in range(n + 1)]
get_in = [0] * (n + 1)
for i in range(m):
    x, y = map(int, input().split())
    graph[x].append(y)
    get_in[y] += 1
stack = []
for i in range(1, n + 1):
    if get_in[i] == 0:
        stack.append(i)
for i in stack:
    for j in graph[i]:
        get_in[j] -= 1
        if get_in[j] == 0:
            stack.append(j)
print(*stack)
