# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/6068
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=6068&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
arr = [tuple(map(int, input().split())) for _ in range(n)]
arr.sort(key=lambda x: x[1])
last = float('inf')
while arr:
    x, y = arr.pop()
    if y <= last:
        last = y - x
    else:
        last -= x
print(last if last >= 0 else -1)
