# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1756
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1756&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
d, n = map(int, input().split())
oven = list(map(int, input().split()))
pizzas = list(map(int, input().split()))
stack = []
for i, v in enumerate(oven):
    if not stack or stack[-1][1] >= v:
        stack.append((i, v))
last_pizza = -1
floor = d
for pizza in pizzas:
    idx = None
    while stack and stack[-1][1] < pizza:
        idx, _ = stack.pop()
    if idx is None:
        if stack:
            last_pizza = floor - 1
        else:
            last_pizza = -1
            break
    else:
        last_pizza = idx - 1
    floor = last_pizza
    if stack and stack[-1][0] == last_pizza:
        stack.pop()
print(last_pizza + 1)
