# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/21939
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=21939&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

entry = set()
difficulty = {}
for _ in range(int(input())):
    p, l = map(int, input().split())
    entry.add((l, p))
    difficulty[p] = l
for _ in range(int(input())):
    s, *r = input().strip().split()
    if s == "add":
        p, l = map(int, r)
        entry.add((l, p))
        difficulty[p] = l
    elif s == "solved":
        p = int(r[0])
        entry.remove((difficulty[p], p))
    elif s == "recommend":
        if r[0] == "1":
            print(max(entry)[1])
        else:
            print(min(entry)[1])
