# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/16437
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=16437&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

n = int(input())
deg = [0] * (n + 1)
sheep = [0] * (n + 1)
parent = [0] * (n + 1)
for idx in range(2, n + 1):
    state, b, c = input().strip().split()
    cnt, adj = int(b), int(c)
    deg[adj] += 1 
    sheep[idx] = cnt if state == 'S' else -cnt
    parent[idx] = adj
que = []
for idx in range(1, n + 1):
    if deg[idx] == 0:
        que.append(idx)
for idx in que:
    if sheep[idx] > 0:
        sheep[parent[idx]] += sheep[idx]
    deg[parent[idx]] -= 1
    if deg[parent[idx]] == 0:
        que.append(parent[idx])
print(sheep[1])
