# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/22860
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=22860&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline


def query(name):
    if name in mapper:
        return mapper[name]
    result = []
    for y, d in graph.get(name, []):
        if d == '0':
            result.append(y)
        else:
            result.extend(query(y))
    mapper[name] = result
    return result


n, m = map(int, input().split())
graph = {}
for _ in range(n + m):
    x, y, d = input().strip().split()
    if x not in graph:
        graph[x] = []
    graph[x].append((y, d))
mapper = {}
for _ in range(int(input())):
    name = input().strip().split("/")[-1]
    result = query(name)
    print(len(set(result)), len(result))
