# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/15989
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=15989&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin

input = stdin.readline

for _ in range(int(input())):
    n = int(input())
    ans = 0
    for r in range(n, -1, -3):
        ans += r // 2 + 1
    print(ans)
