# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/6497
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=6497&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin, setrecursionlimit

input = stdin.readline
setrecursionlimit(10 ** 6)


def find(idx):
    if parent[idx] == idx:
        return idx
    parent[idx] = find(parent[idx])
    return parent[idx]


while True:
    n, m = map(int, input().split())
    if n == 0:
        break
    
    edges = [tuple(map(int, input().split())) for _ in range(m)]
    cost = 0
    for *_, d in edges:
        cost += d
    edges.sort(key=lambda x: x[-1])

    parent = list(range(n))
    c = 0
    for x, y, d in edges:
        fx, fy = find(x), find(y)
        if fx == fy:
            continue
        parent[fx] = fy
        c += 1
        cost -= d
        if c == n - 1:
            break
    print(cost)
