# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/17136
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=17136&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
def check(index):
    global ans, one

    if ans != -1 and sum(used) >= ans:
        return

    x = index // 10
    y = index % 10
    if not 0 <= x < 10 or not 0 <= y < 10:
        return
    if not board[x][y]:
        check(index + 1)
        return

    for i in range(5):
        if x + i >= 10 or y + i >= 10:
            return
        for j in range(i + 1):
            if board[x + i][y + j] == 0 or board[x + j][y + i] == 0:
                return
        if used[i] == 5:
            continue

        for j in range(i + 1):
            for k in range(i + 1):
                board[x + j][y + k] = 0
        used[i] += 1
        one -= (i + 1) ** 2
        if one == 0:
            if ans == -1 or ans > sum(used):
                ans = sum(used)
        check(index + 1)
        for j in range(i + 1):
            for k in range(i + 1):
                board[x + j][y + k] = 1
        used[i] -= 1
        one += (i + 1) ** 2


board = [list(map(int, input().split())) for _ in range(10)]
used = [0] * 5
ans = -1
one = 0
for i in range(10):
    for j in range(10):
        one += board[i][j]
if one == 0:
    print(0)
    exit()
check(0)
print(ans)
