# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2981
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2981&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from math import gcd

n = int(input())
arr = [int(input()) for _ in range(n)]
g = gcd(*[abs(arr[i + 1] - arr[i]) for i in range(n - 1)])
ans = []
for k in range(1, int(g ** 0.5) + 2):
    if g % k == 0:
        ans.append(k)
        ans.append(g // k)
ans = sorted(list(set(ans)))
print(*ans[1:])
