# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1781
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1781&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from sys import stdin
from heapq import heappush, heappop

input = stdin.readline

n = int(input())
arr = [list(map(int, input().split())) for _ in range(n)]
arr.sort()
heap = []
ans = 0
for deadline, prize in arr:
    heappush(heap, prize)
    ans += prize
    if len(heap) > deadline:
        ans -= heappop(heap)
print(ans)
