# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/2529
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=2529&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
from itertools import permutations

n = int(input())
perms = list(permutations(range(0, n + 1)))
ops = input().split()
max_ans = [0] * n
min_ans = [9] * n
for perm in perms:
    perm = list(perm)
    for i in range(n):
        if ops[i] == '<' and perm[i] > perm[i + 1]:
            break
        if ops[i] == '>' and perm[i] < perm[i + 1]:
            break
    else:
        min_ans = perm
        break
for perm in perms[::-1]:
    perm = list(perm)
    for i in range(n):
        if ops[i] == '<' and perm[i] > perm[i + 1]:
            break
        if ops[i] == '>' and perm[i] < perm[i + 1]:
            break
    else:
        max_ans = perm
        break
max_ans = [
    x + (9 - n) for x in max_ans
]
print(''.join(map(str, max_ans)))
print(''.join(map(str, min_ans)))
