# Generated by make_my_study_record.py
# BOJ LINK : https://www.acmicpc.net/problem/1105
# My submission : https://www.acmicpc.net/status?option-status-pid=on&problem_id=1105&user_id=bomul1128&language_id=-1&result_id=-1&from_problem=1
a, b = input().split()
ans = 0
if len(a) == len(b):
    for d in range(len(a)):
        if a[d] == b[d]:
            if a[d] == '8':
                ans += 1
        else:
            break
print(ans)
